apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-world-template
  title: Hello World Template
  description: Hello World Template
spec:
  owner: engineering
  type: service
  parameters: []
  steps:
    - id: backstage_request_with_input
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/catalog/locations'
    - id: log-hello-world
      name: Log Message
      action: debug:log
      input:
        message: 'Hello World!'
  output:
    text:
      - title: Thingy happened
        content: |
          ## 🎉 Your thing did the thing

          **Thingy:** `${{ steps['http:backstage:request'].output.status }}`  


          ### What happened:
          - ✅ Blh blah blah
          blah
          blah
          Blah blah blah blah
