apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-world-template
  title: Hello World Template
  description: Hello World Template
spec:
  owner: engineering
  type: service
  parameters: []
  steps:
    - id: write-file
      name: Create Hello World File
      action: roadiehq:utils:fs:write
      input:
        path: hello-world.txt
        content: |
          Hello World!
          Created by scaffolder template.
    - id: create-pull-request
      name: Create Pull Request
      action: publish:github:pull-request:debug
      input:
        repoUrl: github.com?owner=AcmeInc&repo=blah-template
        branchName: scaffolder/hello-world-${{ now() | date('yyyyMMdd-HHmmss') }}
        title: 'Hello World Template Update'
        description: |
          ## Automated Update

          This PR was created by the Hello World Template scaffolder action.

          **Created at:** ${{ '' | now }}
        targetBranchName: main
  output:
    links:
      - title: GitHub Repository
        icon: github
        url: https://github.com
      - title: Component
        icon: catalog
        url: https://github.com
      - title: System PR
        icon: github
        url: ${{ steps['create-pull-request'].output.remoteUrl }}
    text:
      - title: Thingy happened
        content: |
          ## Your thing did the thing

          **Thingy:** `${{ steps['backstage_request_with_input'].output.status }}`


          ### What happened:
          - Blh blah blah
          blah
          blah
          Blah blah blah blah

          ### Pull Request
          - PR #${{ steps['create-pull-request'].output.pullRequestNumber }}
          - URL: ${{ steps['create-pull-request'].output.remoteUrl }}
