# Tribe and Squad identification
tribe: example
squad: example

security_tools:

  # Secrets Detection
  secrets_detection:
    enabled: 0
    secrets_scanning: 0
    pr_based:
      enabled: 0

  # Static Application Security Testing (SAST)
  sast:
    enabled: 1
    tools:
      codeQL:
        enabled: 1
        config_file_path: '.github/workflows/codeql.yml'
      veracode:
        enabled: 0
      sonarcloud:
        enabled: 1
      sobelow:
        enabled: 0
      credo:
        enabled: 0
      klocwork:
        enabled: 0

  # SCA (Software Composition Analysis)
  sca:
    dependabot:
      enabled: 1
      config_file_path: '.github/dependabot.yml'
    dependency_review:
      enabled: 0

  # Container Security
  container_security:
    trivy:
      enabled: 1
      config_file_path: '.github/workflows/ci.yml'

  # IaC (Infrastructure-as-code) security
  iac_security:
    tfsec:
      enabled: 0

  # Dynamic Application Security Testing (DAST)
  dast:
    zap:
      enabled: 0
