apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta2-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Name of new project
          ui:autofocus: true
          ui:options:
            rows: 5

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: "Hello, about to create this new project asdf ${{ steps.getcomponents.output.code }}"
    - id: create-file
      name: Create file
      action: shell:run
      input:
        command: "touch 1"
    - id: copy-it
      name: Copy a file
      action: shell:run
      input:
        command: "cp 1 2"
    - id: move-it
      name: Move a file
      action: shell:run
      input:
        command: "mv 2 3"
